### ISSUE TITLE
Suggerimento: estendere la timeseries alle altre voci

### ISSUE THREAD

**Issue by andreapede** [lucianolorenti/coronITA#14]
Grazie per la dashboard è molto utile.
Sarebbe utilissimo estendere il primo grafico compresi i trend alle altre voci (mortalità, ospedalizzati, etc etc)

**Comment by lucianolorenti** [comment]
Hi!
Previously, there was the option to visualize that data in the stacked area plots.
Now I added the possibility thanks to #16  to choose between area and line plot,  in the plot that allows comparing between regions and the plot that shows all the data from one region.

https://itacovid-19.herokuapp.com/#People-affected-by-the-virus

**Comment by andreapede** [comment]
Yes, but without the trendline. I was exactly asking if it was possible to extend the trendline that you used in the first plot also to the other plots.

**Comment by lucianolorenti** [comment]
Oooh I think that I understand what are you meaning.
I only put a trending fitted line in the number of infected people because there is as well defined functional form for that quantity, a logistic curve ( I'm fitting an exponetial currently, but I will try to fit a logistic curve today). I really don't know the functional form, or if there is even one, for the other quantities. If you have more information about that I can look at it.

**Comment by andreapede** [comment]
My fault. I also was focused in a specific part of data. From my analyis it seems that a 3rd degree polinomial (cubic) is impressively fitting the died person plot. It is a surprising data, but I'm having less than 1% of error with a 3 day forecast.

**Comment by lucianolorenti** [comment]
I really don't want to put adding a regression curve with any functional shape just because the error is little, or it is relatively little. I do not know of any scientific article that talks about how the number of deaths from this disease evolves. If you know of any please let me know.
